# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export LS_OPTIONS='--color=auto'
eval `dircolors`
alias ls='ls $LS_OPTIONS'
alias grep='grep --color=auto'

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

autoload -U compinit promptinit
compinit
promptinit
 
PROMPT='%~/ > '
RPROMPT='%F{green}%~%f %{%}%D{%Y-%m-%d} %{%}%D{%T}%{%}'
